(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(defalias 'yes-or-no-p 'y-or-n-p)
(delete-selection-mode t)
(column-number-mode t)
(add-to-list 'default-frame-alist '(font . "Monospace-11"))
;;(set-default-font "Monospace-11")
;;(set-face-attribute 'default nil :height 110)
(setq-default indent-tabs-mode nil)
